""" Sends a diff to the Gemini API and returns a review comment. """
from requests import post

_GEMINI_ENDPOINT = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent'

_SYSTEM_PROMPT = (
    'You are a senior software engineer performing a pull request code review. '
    'Review the following unified diff. Point out bugs, security issues, '
    'readability problems, and missing tests. Reply in Japanese using Markdown, '
    'with concrete and concise bullet points. If no issues are found, say so briefly.'
)


def generate_review(diff_text: str, api_key: str) -> str:
    """
        Generate a code review comment for the given diff using Gemini.

        Args:
            diff_text (str): Unified diff content of the pull request.
            api_key   (str): Gemini API key.

        Returns:
            str: Review comment text generated by the model.
    """
    payload = {
        'contents': [
            {
                'role': 'user',
                'parts': [{'text': f'{_SYSTEM_PROMPT}\n\n```diff\n{diff_text}\n```'}]
            }
        ]
    }

    response = post(
        f'{_GEMINI_ENDPOINT}?key={api_key}',
        json=payload,
        timeout=60,
    )
    response.raise_for_status()
    data = response.json()

    candidates = data.get('candidates', [])

    if not candidates:
        return 'レビューコメントを生成できませんでした。'

    parts = candidates[0].get('content', {}).get('parts', [])

    return '\n'.join(part.get('text', '') for part in parts).strip()
